"""Doctor seed data — profiles, schedules, availability, service offerings."""
from .constants import DOW_NAMES, DOW_INT

DOCTORS = [
    {
        "email":      "dr.nguyen.van.an@healthai.dev",
        "password":   "Doctor123!",
        "full_name":  "Dr. Nguyen Van An",
        "title":      "PhD",
        "experience": 15,
        "specialty":  "Cardiology",
        "auto_confirm": True,
        "schedule": {
            "days": DOW_NAMES[:5],
            "start": "08:00:00",
            "end":   "17:00:00",
            "slot":  30,
        },
        "availability": {
            "days": DOW_INT[:5],
            "start": "08:00:00",
            "end":   "17:00:00",
            "break_start": "12:00:00",
            "break_end":   "13:00:00",
            "max_patients": 20,
        },
        "services": [
            {"name": "General Cardiology Consultation", "duration": 30, "fee": 350000},
            {"name": "ECG Reading",                     "duration": 20, "fee": 150000},
            {"name": "Echocardiography",                "duration": 45, "fee": 500000},
        ],
    },
    {
        "email":      "dr.tran.thi.bich@healthai.dev",
        "password":   "Doctor123!",
        "full_name":  "Dr. Tran Thi Bich",
        "title":      "MSc",
        "experience": 10,
        "specialty":  "General Medicine",
        "auto_confirm": True,
        "schedule": {
            "days": DOW_NAMES[:5],
            "start": "07:30:00",
            "end":   "16:30:00",
            "slot":  30,
        },
        "availability": {
            "days": DOW_INT[:5],
            "start": "07:30:00",
            "end":   "16:30:00",
            "break_start": "11:30:00",
            "break_end":   "13:00:00",
            "max_patients": 25,
        },
        "services": [
            {"name": "General Internal Medicine Consultation", "duration": 30, "fee": 180000},
            {"name": "Health Check-up",                       "duration": 20, "fee": 150000},
            {"name": "Chronic Disease Management",            "duration": 30, "fee": 200000},
        ],
    },
    {
        "email":      "dr.le.minh.duc@healthai.dev",
        "password":   "Doctor123!",
        "full_name":  "Dr. Le Minh Duc",
        "title":      "MD",
        "experience": 8,
        "specialty":  "Neurology",
        "auto_confirm": False,
        "schedule": {
            "days": DOW_NAMES[:5] + [DOW_NAMES[5]],  # Mon–Sat
            "start": "08:00:00",
            "end":   "17:00:00",
            "slot":  45,
        },
        "availability": {
            "days": DOW_INT[:6],  # Mon–Sat
            "start": "08:00:00",
            "end":   "17:00:00",
            "break_start": "12:00:00",
            "break_end":   "13:30:00",
            "max_patients": 15,
        },
        "services": [
            {"name": "General Neurology Consultation", "duration": 45, "fee": 400000},
            {"name": "Chronic Headache Consultation",  "duration": 30, "fee": 250000},
        ],
    },
    {
        "email":      "dr.pham.hong.van@healthai.dev",
        "password":   "Doctor123!",
        "full_name":  "Dr. Pham Hong Van",
        "title":      "MSc",
        "experience": 12,
        "specialty":  "Dermatology",
        "auto_confirm": True,
        "schedule": {
            "days": DOW_NAMES[:5],
            "start": "08:00:00",
            "end":   "16:00:00",
            "slot":  30,
        },
        "availability": {
            "days": DOW_INT[:5],
            "start": "08:00:00",
            "end":   "16:00:00",
            "break_start": "12:00:00",
            "break_end":   "13:00:00",
            "max_patients": 20,
        },
        "services": [
            {"name": "General Dermatology Consultation", "duration": 30, "fee": 250000},
            {"name": "Acne Treatment",                   "duration": 30, "fee": 300000},
            {"name": "Skincare Counseling",              "duration": 20, "fee": 180000},
        ],
    },
    {
        "email":      "dr.vo.thanh.tung@healthai.dev",
        "password":   "Doctor123!",
        "full_name":  "Dr. Vo Thanh Tung",
        "title":      "PhD",
        "experience": 20,
        "specialty":  "General Medicine",
        "auto_confirm": True,
        "schedule": {
            "days": DOW_NAMES[:5],
            "start": "08:00:00",
            "end":   "17:00:00",
            "slot":  30,
        },
        "availability": {
            "days": DOW_INT[:5],
            "start": "08:00:00",
            "end":   "17:00:00",
            "break_start": "12:00:00",
            "break_end":   "13:00:00",
            "max_patients": 18,
        },
        "services": [
            {"name": "General Internal Medicine Consultation", "duration": 30, "fee": 180000},
            {"name": "Geriatric Health Assessment",            "duration": 30, "fee": 220000},
            {"name": "Preventive Medicine Consultation",       "duration": 20, "fee": 150000},
        ],
    },
    {
        "email":      "dr.pham.thi.lan.huong@healthai.dev",
        "password":   "Doctor123!",
        "full_name":  "Dr. Pham Thi Lan Huong",
        "title":      "PhD",
        "experience": 14,
        "specialty":  "Pediatrics",
        "auto_confirm": True,
        "schedule": {
            "days": DOW_NAMES[:5],
            "start": "08:00:00",
            "end":   "16:30:00",
            "slot":  30,
        },
        "availability": {
            "days": DOW_INT[:5],
            "start": "08:00:00",
            "end":   "16:30:00",
            "break_start": "12:00:00",
            "break_end":   "13:00:00",
            "max_patients": 20,
        },
        "services": [
            {"name": "General Pediatrics Consultation",  "duration": 30, "fee": 280000},
            {"name": "Child Developmental Assessment",   "duration": 30, "fee": 250000},
            {"name": "Vaccination & Immunization",       "duration": 20, "fee": 150000},
        ],
    },
    {
        "email":      "dr.hoang.van.minh@healthai.dev",
        "password":   "Doctor123!",
        "full_name":  "Dr. Hoang Van Minh",
        "title":      "PhD",
        "experience": 18,
        "specialty":  "General Surgery",
        "auto_confirm": False,
        "schedule": {
            "days": DOW_NAMES[:5],
            "start": "08:00:00",
            "end":   "17:00:00",
            "slot":  30,
        },
        "availability": {
            "days": DOW_INT[:5],
            "start": "08:00:00",
            "end":   "17:00:00",
            "break_start": "12:00:00",
            "break_end":   "13:00:00",
            "max_patients": 15,
        },
        "services": [
            {"name": "General Surgery Consultation",    "duration": 30, "fee": 350000},
            {"name": "Abdominal Surgery Evaluation",    "duration": 45, "fee": 400000},
            {"name": "Pre-operative Assessment",        "duration": 30, "fee": 280000},
        ],
    },
    {
        "email":      "dr.nguyen.thi.hue.linh@healthai.dev",
        "password":   "Doctor123!",
        "full_name":  "Dr. Nguyen Thi Hue Linh",
        "title":      "MSc",
        "experience": 12,
        "specialty":  "ENT",
        "auto_confirm": True,
        "schedule": {
            "days": DOW_NAMES[:5],
            "start": "08:00:00",
            "end":   "16:00:00",
            "slot":  30,
        },
        "availability": {
            "days": DOW_INT[:5],
            "start": "08:00:00",
            "end":   "16:00:00",
            "break_start": "12:00:00",
            "break_end":   "13:00:00",
            "max_patients": 15,
        },
        "services": [
            {"name": "General ENT Consultation",        "duration": 30, "fee": 280000},
            {"name": "Hearing & Ear Assessment",        "duration": 30, "fee": 250000},
            {"name": "Sinusitis & Nasal Disorder Care", "duration": 30, "fee": 230000},
        ],
    },
    {
        "email":      "dr.tran.van.phuong@healthai.dev",
        "password":   "Doctor123!",
        "full_name":  "Dr. Tran Van Phuong",
        "title":      "MD",
        "experience": 16,
        "specialty":  "Ophthalmology",
        "auto_confirm": False,
        "schedule": {
            "days": DOW_NAMES[:5],
            "start": "08:00:00",
            "end":   "17:00:00",
            "slot":  30,
        },
        "availability": {
            "days": DOW_INT[:5],
            "start": "08:00:00",
            "end":   "17:00:00",
            "break_start": "12:00:00",
            "break_end":   "13:00:00",
            "max_patients": 18,
        },
        "services": [
            {"name": "General Ophthalmology Consultation", "duration": 30, "fee": 300000},
            {"name": "Vision & Refraction Assessment",     "duration": 30, "fee": 250000},
            {"name": "Cataract & Glaucoma Screening",      "duration": 30, "fee": 280000},
        ],
    },
]
