"""Patient seed data — one entry per patient linked to their primary doctor."""

PATIENTS = [
    # ── Cardiology (Dr. Nguyen Van An) ──────────────────────────────────────
    {
        "email":        "patient.le.thi.mai@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Le Thi Mai",
        "dob":          "1982-06-10",
        "gender":       "FEMALE",
        "phone":        "0912345678",
        "address":      "45 Nguyen Hue, Ho Chi Minh City",
        "blood_type":   "A",
        "height_cm":    162,
        "weight_kg":    56.5,
        "allergies":    ["aspirin"],
        "conditions":   ["hypertension"],
        "doctor_email": "dr.nguyen.van.an@healthai.dev",
    },
    {
        "email":        "patient.tran.van.long@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Tran Van Long",
        "dob":          "1975-11-22",
        "gender":       "MALE",
        "phone":        "0923456789",
        "address":      "78 Le Duan, Ho Chi Minh City",
        "blood_type":   "O",
        "height_cm":    172,
        "weight_kg":    75.0,
        "allergies":    [],
        "conditions":   ["type 2 diabetes", "hypertension"],
        "doctor_email": "dr.nguyen.van.an@healthai.dev",
    },
    {
        "email":        "patient.vo.thi.hoa@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Vo Thi Hoa",
        "dob":          "1990-04-05",
        "gender":       "FEMALE",
        "phone":        "0934567890",
        "address":      "22 Pasteur, Ho Chi Minh City",
        "blood_type":   "B",
        "height_cm":    155,
        "weight_kg":    50.0,
        "allergies":    ["penicillin"],
        "conditions":   [],
        "doctor_email": "dr.nguyen.van.an@healthai.dev",
    },
    # ── General Medicine (Dr. Tran Thi Bich) ────────────────────────────────
    {
        "email":        "patient.nguyen.van.minh@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Nguyen Van Minh",
        "dob":          "2018-08-14",
        "gender":       "MALE",
        "phone":        "0945678901",
        "address":      "10 Hoang Van Thu, Ho Chi Minh City",
        "blood_type":   "AB",
        "height_cm":    110,
        "weight_kg":    20.0,
        "allergies":    ["dust mites"],
        "conditions":   ["asthma"],
        "doctor_email": "dr.tran.thi.bich@healthai.dev",
    },
    {
        "email":        "patient.pham.thi.lan@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Pham Thi Lan",
        "dob":          "2015-02-28",
        "gender":       "FEMALE",
        "phone":        "0956789012",
        "address":      "35 Cach Mang Thang 8, Ho Chi Minh City",
        "blood_type":   "A",
        "height_cm":    125,
        "weight_kg":    26.0,
        "allergies":    [],
        "conditions":   [],
        "doctor_email": "dr.tran.thi.bich@healthai.dev",
    },
    {
        "email":        "patient.dao.van.cuong@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Dao Van Cuong",
        "dob":          "2020-11-05",
        "gender":       "MALE",
        "phone":        "0967890123",
        "address":      "58 Nguyen Dinh Chieu, Ho Chi Minh City",
        "blood_type":   "B",
        "height_cm":    95,
        "weight_kg":    14.0,
        "allergies":    ["eggs"],
        "conditions":   [],
        "doctor_email": "dr.tran.thi.bich@healthai.dev",
    },
    # ── Neurology (Dr. Le Minh Duc) ─────────────────────────────────────────
    {
        "email":        "patient.hoang.thi.thu@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Hoang Thi Thu",
        "dob":          "1978-09-19",
        "gender":       "FEMALE",
        "phone":        "0978901234",
        "address":      "14 Dien Bien Phu, Ho Chi Minh City",
        "blood_type":   "O",
        "height_cm":    160,
        "weight_kg":    58.0,
        "allergies":    [],
        "conditions":   ["migraine"],
        "doctor_email": "dr.le.minh.duc@healthai.dev",
    },
    {
        "email":        "patient.bui.van.duc@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Bui Van Duc",
        "dob":          "1965-03-30",
        "gender":       "MALE",
        "phone":        "0989012345",
        "address":      "99 Vo Thi Sau, Ho Chi Minh City",
        "blood_type":   "A",
        "height_cm":    168,
        "weight_kg":    72.0,
        "allergies":    [],
        "conditions":   ["epilepsy"],
        "doctor_email": "dr.le.minh.duc@healthai.dev",
    },
    {
        "email":        "patient.ly.thi.tuyet@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Ly Thi Tuyet",
        "dob":          "1995-07-12",
        "gender":       "FEMALE",
        "phone":        "0990123456",
        "address":      "25 Nguyen Trai, Ho Chi Minh City",
        "blood_type":   "AB",
        "height_cm":    156,
        "weight_kg":    48.0,
        "allergies":    ["ibuprofen"],
        "conditions":   ["chronic headache"],
        "doctor_email": "dr.le.minh.duc@healthai.dev",
    },
    # ── Dermatology (Dr. Pham Hong Van) ─────────────────────────────────────
    {
        "email":        "patient.duong.van.khanh@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Duong Van Khanh",
        "dob":          "1992-12-01",
        "gender":       "MALE",
        "phone":        "0901234560",
        "address":      "7 Tran Hung Dao, Ho Chi Minh City",
        "blood_type":   "B",
        "height_cm":    175,
        "weight_kg":    68.0,
        "allergies":    ["latex"],
        "conditions":   ["eczema"],
        "doctor_email": "dr.pham.hong.van@healthai.dev",
    },
    {
        "email":        "patient.ngo.thi.xuan@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Ngo Thi Xuan",
        "dob":          "1988-05-17",
        "gender":       "FEMALE",
        "phone":        "0912345670",
        "address":      "31 Nam Ky Khoi Nghia, Ho Chi Minh City",
        "blood_type":   "O",
        "height_cm":    157,
        "weight_kg":    52.0,
        "allergies":    [],
        "conditions":   ["psoriasis"],
        "doctor_email": "dr.pham.hong.van@healthai.dev",
    },
    {
        "email":        "patient.trinh.van.hung@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Trinh Van Hung",
        "dob":          "2000-08-25",
        "gender":       "MALE",
        "phone":        "0923456780",
        "address":      "62 Phan Xich Long, Ho Chi Minh City",
        "blood_type":   "A",
        "height_cm":    178,
        "weight_kg":    70.0,
        "allergies":    ["sulfa drugs"],
        "conditions":   ["acne vulgaris"],
        "doctor_email": "dr.pham.hong.van@healthai.dev",
    },
    # ── General Medicine (Dr. Vo Thanh Tung) ────────────────────────────────
    {
        "email":        "patient.mai.thi.lien@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Mai Thi Lien",
        "dob":          "1970-04-08",
        "gender":       "FEMALE",
        "phone":        "0934567891",
        "address":      "18 Hai Ba Trung, Ho Chi Minh City",
        "blood_type":   "AB",
        "height_cm":    154,
        "weight_kg":    60.0,
        "allergies":    [],
        "conditions":   ["osteoarthritis"],
        "doctor_email": "dr.vo.thanh.tung@healthai.dev",
    },
    {
        "email":        "patient.cao.van.toan@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Cao Van Toan",
        "dob":          "1958-12-14",
        "gender":       "MALE",
        "phone":        "0945678902",
        "address":      "85 Mac Dinh Chi, Ho Chi Minh City",
        "blood_type":   "O",
        "height_cm":    170,
        "weight_kg":    78.0,
        "allergies":    [],
        "conditions":   ["rheumatoid arthritis", "osteoporosis"],
        "doctor_email": "dr.vo.thanh.tung@healthai.dev",
    },
    {
        "email":        "patient.nguyen.thi.nga@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Nguyen Thi Nga",
        "dob":          "1986-01-20",
        "gender":       "FEMALE",
        "phone":        "0956789013",
        "address":      "41 Tran Quoc Toan, Ho Chi Minh City",
        "blood_type":   "B",
        "height_cm":    160,
        "weight_kg":    55.0,
        "allergies":    ["NSAIDs"],
        "conditions":   ["knee injury"],
        "doctor_email": "dr.vo.thanh.tung@healthai.dev",
    },
    # ── Respiratory (Dr. Pham Thi Lan Huong) ────────────────────────────────
    {
        "email":        "patient.pham.van.khang@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Pham Van Khang",
        "dob":          "1978-07-15",
        "gender":       "MALE",
        "phone":        "0901234567",
        "address":      "20 Nguyen Du, Ho Chi Minh City",
        "blood_type":   "A",
        "height_cm":    168,
        "weight_kg":    72.0,
        "allergies":    [],
        "conditions":   ["COPD", "hypertension"],
        "doctor_email": "dr.pham.thi.lan.huong@healthai.dev",
    },
    {
        "email":        "patient.luu.thi.mai@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Luu Thi Mai",
        "dob":          "1985-03-22",
        "gender":       "FEMALE",
        "phone":        "0912345671",
        "address":      "33 Ly Thai To, Ho Chi Minh City",
        "blood_type":   "O",
        "height_cm":    158,
        "weight_kg":    54.0,
        "allergies":    ["dust mites"],
        "conditions":   ["asthma"],
        "doctor_email": "dr.pham.thi.lan.huong@healthai.dev",
    },
    {
        "email":        "patient.tran.van.nam@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Tran Van Nam",
        "dob":          "1992-10-08",
        "gender":       "MALE",
        "phone":        "0923456781",
        "address":      "47 Nguyen Hue, Ho Chi Minh City",
        "blood_type":   "B",
        "height_cm":    175,
        "weight_kg":    80.0,
        "allergies":    [],
        "conditions":   ["pneumonia history"],
        "doctor_email": "dr.pham.thi.lan.huong@healthai.dev",
    },
    # ── Nephrology (Dr. Hoang Van Minh) ─────────────────────────────────────
    {
        "email":        "patient.dinh.thi.lan@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Dinh Thi Lan",
        "dob":          "1965-09-14",
        "gender":       "FEMALE",
        "phone":        "0934567892",
        "address":      "55 Le Lai, Ho Chi Minh City",
        "blood_type":   "A",
        "height_cm":    156,
        "weight_kg":    62.0,
        "allergies":    [],
        "conditions":   ["type 2 diabetes", "CKD stage 3"],
        "doctor_email": "dr.hoang.van.minh@healthai.dev",
    },
    {
        "email":        "patient.le.van.son@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Le Van Son",
        "dob":          "1950-12-03",
        "gender":       "MALE",
        "phone":        "0945678903",
        "address":      "67 Pham Ngu Lao, Ho Chi Minh City",
        "blood_type":   "AB",
        "height_cm":    165,
        "weight_kg":    70.0,
        "allergies":    [],
        "conditions":   ["hypertension", "chronic kidney disease"],
        "doctor_email": "dr.hoang.van.minh@healthai.dev",
    },
    {
        "email":        "patient.nguyen.thi.thanh@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Nguyen Thi Thanh",
        "dob":          "1977-06-28",
        "gender":       "FEMALE",
        "phone":        "0956789014",
        "address":      "29 Truong Chinh, Ho Chi Minh City",
        "blood_type":   "O",
        "height_cm":    155,
        "weight_kg":    58.0,
        "allergies":    ["iodine contrast"],
        "conditions":   ["recurrent urinary tract infections"],
        "doctor_email": "dr.hoang.van.minh@healthai.dev",
    },
    # ── Hematology (Dr. Nguyen Thi Hue Linh) ────────────────────────────────
    {
        "email":        "patient.vu.thi.hang@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Vu Thi Hang",
        "dob":          "1988-11-17",
        "gender":       "FEMALE",
        "phone":        "0967890124",
        "address":      "38 Nguyen Tri Phuong, Ho Chi Minh City",
        "blood_type":   "B",
        "height_cm":    157,
        "weight_kg":    52.0,
        "allergies":    [],
        "conditions":   ["iron deficiency anemia"],
        "doctor_email": "dr.nguyen.thi.hue.linh@healthai.dev",
    },
    {
        "email":        "patient.phan.van.thanh@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Phan Van Thanh",
        "dob":          "1960-02-25",
        "gender":       "MALE",
        "phone":        "0978901235",
        "address":      "72 Dong Khoi, Ho Chi Minh City",
        "blood_type":   "A",
        "height_cm":    172,
        "weight_kg":    75.0,
        "allergies":    [],
        "conditions":   ["chronic lymphocytic leukemia"],
        "doctor_email": "dr.nguyen.thi.hue.linh@healthai.dev",
    },
    {
        "email":        "patient.hoang.thi.phuong@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Hoang Thi Phuong",
        "dob":          "1995-08-09",
        "gender":       "FEMALE",
        "phone":        "0989012346",
        "address":      "15 Nam Ky Khoi Nghia, Ho Chi Minh City",
        "blood_type":   "O",
        "height_cm":    161,
        "weight_kg":    50.0,
        "allergies":    [],
        "conditions":   ["thrombocytopenia"],
        "doctor_email": "dr.nguyen.thi.hue.linh@healthai.dev",
    },
    # ── Endocrinology (Dr. Tran Van Phuong) ─────────────────────────────────
    {
        "email":        "patient.bui.thi.linh@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Bui Thi Linh",
        "dob":          "1972-05-30",
        "gender":       "FEMALE",
        "phone":        "0990123457",
        "address":      "42 Cach Mang Thang 8, Ho Chi Minh City",
        "blood_type":   "AB",
        "height_cm":    158,
        "weight_kg":    68.0,
        "allergies":    [],
        "conditions":   ["type 2 diabetes", "hypertension", "obesity"],
        "doctor_email": "dr.tran.van.phuong@healthai.dev",
    },
    {
        "email":        "patient.do.van.hung@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Do Van Hung",
        "dob":          "1955-09-11",
        "gender":       "MALE",
        "phone":        "0901234568",
        "address":      "60 Pasteur, Ho Chi Minh City",
        "blood_type":   "A",
        "height_cm":    167,
        "weight_kg":    82.0,
        "allergies":    [],
        "conditions":   ["hypothyroidism", "dyslipidemia"],
        "doctor_email": "dr.tran.van.phuong@healthai.dev",
    },
    {
        "email":        "patient.truong.thi.mai@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Truong Thi Mai",
        "dob":          "1983-12-19",
        "gender":       "FEMALE",
        "phone":        "0912345672",
        "address":      "88 Nguyen Trai, Ho Chi Minh City",
        "blood_type":   "B",
        "height_cm":    160,
        "weight_kg":    56.0,
        "allergies":    [],
        "conditions":   ["hyperthyroidism"],
        "doctor_email": "dr.tran.van.phuong@healthai.dev",
    },
    # ── 4th patients — NO_SHOW appointments ─────────────────────────────────
    {
        "email":        "patient.le.thi.nam@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Le Thi Nam",
        "dob":          "1970-08-15",
        "gender":       "FEMALE",
        "phone":        "0909888777",
        "address":      "15 Nguyen Hue, Ho Chi Minh City",
        "blood_type":   "AB",
        "height_cm":    168,
        "weight_kg":    72.0,
        "allergies":    [],
        "conditions":   ["atrial fibrillation"],
        "doctor_email": "dr.nguyen.van.an@healthai.dev",
    },
    {
        "email":        "patient.nguyen.thi.thao@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Nguyen Thi Thao",
        "dob":          "2012-03-20",
        "gender":       "FEMALE",
        "phone":        "0909888778",
        "address":      "25 Hoang Van Thu, Ho Chi Minh City",
        "blood_type":   "O",
        "height_cm":    140,
        "weight_kg":    35.0,
        "allergies":    ["shellfish"],
        "conditions":   [],
        "doctor_email": "dr.tran.thi.bich@healthai.dev",
    },
    {
        "email":        "patient.pham.van.tuan@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Pham Van Tuan",
        "dob":          "1988-11-05",
        "gender":       "MALE",
        "phone":        "0909888779",
        "address":      "33 Dien Bien Phu, Ho Chi Minh City",
        "blood_type":   "A",
        "height_cm":    170,
        "weight_kg":    68.0,
        "allergies":    [],
        "conditions":   ["insomnia"],
        "doctor_email": "dr.le.minh.duc@healthai.dev",
    },
    {
        "email":        "patient.hoang.thi.lan@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Hoang Thi Lan",
        "dob":          "1996-07-30",
        "gender":       "FEMALE",
        "phone":        "0909888780",
        "address":      "42 Pasteur, Ho Chi Minh City",
        "blood_type":   "B",
        "height_cm":    158,
        "weight_kg":    52.0,
        "allergies":    [],
        "conditions":   ["contact dermatitis"],
        "doctor_email": "dr.pham.hong.van@healthai.dev",
    },
    {
        "email":        "patient.tran.van.hung@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Tran Van Hung",
        "dob":          "1962-02-14",
        "gender":       "MALE",
        "phone":        "0909888781",
        "address":      "58 Mac Dinh Chi, Ho Chi Minh City",
        "blood_type":   "O",
        "height_cm":    165,
        "weight_kg":    74.0,
        "allergies":    ["codeine"],
        "conditions":   ["lumbar spondylosis"],
        "doctor_email": "dr.vo.thanh.tung@healthai.dev",
    },
    {
        "email":        "patient.vu.thi.hue@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Vu Thi Hue",
        "dob":          "1980-05-10",
        "gender":       "FEMALE",
        "phone":        "0909888782",
        "address":      "70 Nguyen Du, Ho Chi Minh City",
        "blood_type":   "A",
        "height_cm":    162,
        "weight_kg":    58.0,
        "allergies":    [],
        "conditions":   ["bronchitis"],
        "doctor_email": "dr.pham.thi.lan.huong@healthai.dev",
    },
    {
        "email":        "patient.dang.thi.mai@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Dang Thi Mai",
        "dob":          "1975-12-22",
        "gender":       "FEMALE",
        "phone":        "0909888783",
        "address":      "88 Le Lai, Ho Chi Minh City",
        "blood_type":   "AB",
        "height_cm":    155,
        "weight_kg":    60.0,
        "allergies":    [],
        "conditions":   ["type 2 diabetes", "hypertension"],
        "doctor_email": "dr.hoang.van.minh@healthai.dev",
    },
    {
        "email":        "patient.ngo.van.minh@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Ngo Van Minh",
        "dob":          "1965-01-25",
        "gender":       "MALE",
        "phone":        "0909888787",
        "address":      "90 Dong Khoi, Ho Chi Minh City",
        "blood_type":   "A",
        "height_cm":    170,
        "weight_kg":    74.0,
        "allergies":    [],
        "conditions":   ["hemophilia A"],
        "doctor_email": "dr.nguyen.thi.hue.linh@healthai.dev",
    },
    {
        "email":        "patient.luu.thi.hue@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Luu Thi Hue",
        "dob":          "1974-09-30",
        "gender":       "FEMALE",
        "phone":        "0909888788",
        "address":      "66 Pasteur, Ho Chi Minh City",
        "blood_type":   "AB",
        "height_cm":    155,
        "weight_kg":    62.0,
        "allergies":    [],
        "conditions":   ["polycystic ovary syndrome"],
        "doctor_email": "dr.tran.van.phuong@healthai.dev",
    },
    # ── 5th patients — OVERDUE appointments ─────────────────────────────────
    {
        "email":        "patient.phan.thi.mai@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Phan Thi Mai",
        "dob":          "1990-10-03",
        "gender":       "FEMALE",
        "phone":        "0909888786",
        "address":      "55 Nguyen Du, Ho Chi Minh City",
        "blood_type":   "O",
        "height_cm":    160,
        "weight_kg":    54.0,
        "allergies":    [],
        "conditions":   ["pulmonary fibrosis"],
        "doctor_email": "dr.pham.thi.lan.huong@healthai.dev",
    },
    {
        "email":        "patient.hoang.van.tuan@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Hoang Van Tuan",
        "dob":          "1955-06-17",
        "gender":       "MALE",
        "phone":        "0909888790",
        "address":      "72 Le Lai, Ho Chi Minh City",
        "blood_type":   "A",
        "height_cm":    168,
        "weight_kg":    78.0,
        "allergies":    [],
        "conditions":   ["urinary incontinence"],
        "doctor_email": "dr.hoang.van.minh@healthai.dev",
    },
    {
        "email":        "patient.truong.thi.lan@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Truong Thi Lan",
        "dob":          "1982-04-11",
        "gender":       "FEMALE",
        "phone":        "0909888791",
        "address":      "82 Nam Ky Khoi Nghia, Ho Chi Minh City",
        "blood_type":   "O",
        "height_cm":    158,
        "weight_kg":    55.0,
        "allergies":    [],
        "conditions":   ["sickle cell trait"],
        "doctor_email": "dr.nguyen.thi.hue.linh@healthai.dev",
    },
    {
        "email":        "patient.phan.van.lap@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Phan Van Lap",
        "dob":          "1960-07-08",
        "gender":       "MALE",
        "phone":        "0909888792",
        "address":      "78 Pasteur, Ho Chi Minh City",
        "blood_type":   "B",
        "height_cm":    168,
        "weight_kg":    85.0,
        "allergies":    [],
        "conditions":   ["Cushing syndrome"],
        "doctor_email": "dr.tran.van.phuong@healthai.dev",
    },
    {
        "email":        "patient.vo.thi.huong@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Vo Thi Huong",
        "dob":          "1978-03-25",
        "gender":       "FEMALE",
        "phone":        "0909888793",
        "address":      "50 Nguyen Hue, Ho Chi Minh City",
        "blood_type":   "A",
        "height_cm":    158,
        "weight_kg":    56.0,
        "allergies":    [],
        "conditions":   ["mitral valve prolapse"],
        "doctor_email": "dr.nguyen.van.an@healthai.dev",
    },
    {
        "email":        "patient.le.thanh.dat@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Le Thanh Dat",
        "dob":          "2010-12-15",
        "gender":       "MALE",
        "phone":        "0909888794",
        "address":      "38 Hoang Van Thu, Ho Chi Minh City",
        "blood_type":   "B",
        "height_cm":    145,
        "weight_kg":    40.0,
        "allergies":    ["peanuts"],
        "conditions":   ["type 1 diabetes"],
        "doctor_email": "dr.tran.thi.bich@healthai.dev",
    },
    {
        "email":        "patient.nguyen.thi.cuc@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Nguyen Thi Cuc",
        "dob":          "1992-08-19",
        "gender":       "FEMALE",
        "phone":        "0909888795",
        "address":      "44 Dien Bien Phu, Ho Chi Minh City",
        "blood_type":   "O",
        "height_cm":    162,
        "weight_kg":    58.0,
        "allergies":    [],
        "conditions":   ["multiple sclerosis"],
        "doctor_email": "dr.le.minh.duc@healthai.dev",
    },
    {
        "email":        "patient.dang.thi.huong@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Dang Thi Huong",
        "dob":          "1985-11-22",
        "gender":       "FEMALE",
        "phone":        "0909888796",
        "address":      "60 Pasteur, Ho Chi Minh City",
        "blood_type":   "B",
        "height_cm":    156,
        "weight_kg":    53.0,
        "allergies":    [],
        "conditions":   ["alopecia areata"],
        "doctor_email": "dr.pham.hong.van@healthai.dev",
    },
    {
        "email":        "patient.huynh.thi.mai@healthai.dev",
        "password":     "Patient123!",
        "full_name":    "Huynh Thi Mai",
        "dob":          "1968-05-04",
        "gender":       "FEMALE",
        "phone":        "0909888797",
        "address":      "66 Mac Dinh Chi, Ho Chi Minh City",
        "blood_type":   "A",
        "height_cm":    152,
        "weight_kg":    64.0,
        "allergies":    [],
        "conditions":   ["hip osteoarthritis"],
        "doctor_email": "dr.vo.thanh.tung@healthai.dev",
    },
]
